version: '3'

services:
  shell-web:
    build:
      context: ./dockerfiles
      dockerfile: ng.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: shell-web
    volumes:
      - ./src:/src
    working_dir: /src/web
    ports:
      - 4200:4200
    command: nx serve --host 0.0.0.0 --poll 2000

  shell-backend:
    build:
      context: ./dockerfiles
      dockerfile: ng.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: shell-backend
    volumes:
      - ./src:/src
    working_dir: /src/web
    depends_on:
      - mongo
    ports:
      - 3333:3333
    command: nx serve backend

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
